AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Authorizer using JWT and JWKS (Auth0-compatible)

Globals:
  Function:
    Runtime: nodejs22.x
    Timeout: 10
    MemorySize: 128

Resources:
  JwtAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: jwt-authorizer
      Handler: index.handler
      CodeUri: ./aws-auth0-lambda-authorizer.zip
      PackageType: Zip
      Environment:
        Variables:
          AUDIENCE: !Ref Audience
          TOKEN_ISSUER: !Ref TokenIssuer
          JWKS_URI: !Ref JwksUri
      Policies:
        - AWSLambdaBasicExecutionRole
      Description: Custom JWT authorizer with JWKS for API Gateway
      Architectures:
        - x86_64

Parameters:
  Audience:
    Type: String
    Description: Expected audience claim in the JWT

  TokenIssuer:
    Type: String
    Description: Expected issuer of the JWT

  JwksUri:
    Type: String
    Description: JWKS endpoint URI (e.g. https://tenant.auth0.com/.well-known/jwks.json)

Outputs:
  JwtAuthorizerFunctionArn:
    Description: ARN of the deployed Lambda authorizer function
    Value: !GetAtt JwtAuthorizerFunction.Arn
